import "../styles/globals.css";
import "../styles/home.scss";
import NavBar from "@/components/NavBar";
import RowSlide from "@/components/RowSlide";
import { Noto_Sans_JP, Montserrat } from "next/font/google";

const notojp = Noto_Sans_JP({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-notojp",
});

const mont = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body
        className={`min-h-screen text-dark bg-light ${mont.variable} ${notojp.variable} font-notojp `}
      >
        <NavBar />
        <RowSlide>{children}</RowSlide>
      </body>
    </html>
  );
}
