import "../styles/globals.css";
import "../styles/home.scss";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import RowSlide from "@/components/RowSlide";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`min-h-screen text-dark bg-light ${inter.className} `}>
        <NavBar />
        <RowSlide>{children}</RowSlide>
      </body>
    </html>
  );
}
